name: Docker Test
on: push

jobs:
  test-docker-container:
    runs-on: ubuntu-latest
    container:
      image: 21-alpine3.17
      env: 
        NODE_ENV: develpment
      ports:
        - 80
    steps:
      - name: Display Node Version
        run: |
          node -v
          cat /etc/os-release